# remotely use Pitt HTC cluster
# R= 4.0.0
setwd("/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs")

library(dplyr) # for separate(), %>%, bind_rows()
library(tidyr) # for separate(), %>%
library(ggplot2)
library(gridExtra) # for grid.arrange()
library(LSD) # for heatscatter()

##### 0. functions & common info #####
# 0.1 dataframe of 811 motifs
mtf811_info <- data.frame(mtf_name = c('AYR', 'BYR', 'ARY', 'NYR','NNN','ANN'),
                          mtfs = I(list(c("AYR"), c("BYR"), c("ARY"), c('AYR','BYR'),
                                        c('AYR','BYR', 'ARY'), c("AYR","ARY"))))
# 0.2 function for visualization
heatscatter_vis <- function(x, y, main, xlab, ylab, xlim=NULL, ylim=NULL,cex.main=2,
                            tick=TRUE,
                            diagonal=TRUE, vline=FALSE, hline=FALSE){
  par(mar=c(4.5, 5, 3, 1), lwd=4, pty="s")
  heatscatter(x=x, y=y,
              colpal="bl2gr2rd",
              xlim=xlim, ylim=ylim, xaxt="n", yaxt="n",
              main="", xlab=xlab, ylab=ylab,
              cex.lab=2.5, cex.axis=2)
  title(main=main, cex.main=cex.main)
  axis(side=1, tick=tick, cex.axis = 2)
  axis(side=2, tick=tick, cex.axis = 2)
  if(diagonal){abline(coef = c(0,1), col="grey", lwd=3, lty=2)}
  if(vline){abline(v= vline, col= "red", lty = 2, lwd= 3)}
  if(hline){abline(h= hline, col= "red", lty = 2, lwd= 3)}
}

##### 1. dataset setup ##### 
## 1.1. get all data generated from MASTER libraries generated by <5-eff-84_seqn11p9_info_mtx.py>
master_mtx_file = paste0("/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/",
                         "all-pDs_B12RepsCmb-ct4-eff-84_seqn11p9_info_mtx.csv")
master_mtx <- read.csv(master_mtx_file, colClasses=c("numeric",rep("factor",24)))
  # 25 columns: [eff] - [pos-11to+9]*20 - [annotations]*4
  # "eff", "n11"-"p9", "PolII","lib","TSS","TSSvar"
  # 4720560      25

master_mtx <- master_mtx[!(is.na(master_mtx$eff)),] # only keep rows w/o NA for eff; => 4714146
for (p in seq(2,21,1)){
  master_mtx[,p] <- factor(master_mtx[,p], levels=c('A','G','C','T')) # to re-ORDER levels
}
rm(p, master_mtx_file)

dim(master_mtx) # 4714146      25
table(master_mtx$lib, master_mtx$TSS)

##### 2. median-based analysis of subgroups; -11 to +1 => interactions; => mut-WT #####
## 2.1 "relative efficiency" at positions -11 to +1, using different datasets ----
pol = 'WT' # c('WT','E1103G','F1086S','G1097D','H1085Q')
Libs = 'NYR' # c('AYR','BYR','ARY','NYR','NNN','ANN')
tss = '1' # '-8' to '4'
sub_mtx <- subset(master_mtx, PolII == pol & lib %in% unlist(mtf811_info[mtf811_info$mtf_name==Libs,'mtfs']) & TSS == tss)
table(sub_mtx$lib,sub_mtx$TSS)

df <- data.frame(base=c('A','G','C','T'))
for (pos in c('n11','n10','n9','n8','n7','n6','n5','n4','n3','n2','n1','p1')){
  temp = aggregate(eff ~ eval(as.symbol(pos)), data=sub_mtx, FUN=median)
  df <- merge(df,temp,by.x = 'base', by.y = 'eval(as.symbol(pos))', all=TRUE)
  colnames(df)[ncol(df)] = pos
}
rownames(df) <- df$base
final <- subset(df, select = -base)
for (pos in c('n11','n10','n9','n8','n7','n6','n5','n4','n3','n2','n1','p1')){
  for (base in c('A','G','C','T')){
    final[base, pos] = df[base, pos] - mean(df[, pos], na.rm=TRUE)
  }
}
final[is.na(final)] <- 0

out_folder = "/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/6-ct4-pos_pref_centered/"
write.csv(t(final[c('A','G','C','T'),]), paste0(out_folder, Libs,"_",tss,"eff_median_centered.csv"), row.names = TRUE)
rm(df,temp,final,pos,base, Libs,pol,tss)

## 2.2 interactions between (-11 to +1) and (-11 to +1) ----
pol = 'WT' # c('WT','E1103G','F1086S','G1097D','H1085Q')
out_folder = "/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/6-ct4-itr_centered/"
all_centered <- data.frame()
for (fix_pos in c('n11','n10','n9','n8','n7','n6','n5','n4','n3','n2','n1','p1')){
  # interaction between (-11 to -9) vs (-11 to -3): [NNN +4 TSS] dataset is used
  if (fix_pos %in% c('n11','n10','n9')){
    df <- data.frame(base=c('A','G','C','T'))
    sub_mtx <- subset(master_mtx, PolII == pol & lib %in% c('AYR','BYR','ARY') & TSS == '4')
    for (pos in c('n11','n10','n9','n8','n7','n6','n5','n4','n3')){
      for (fix_base in c('A','G','C','T')){
        temp = aggregate(eff ~ eval(as.symbol(pos)), data=subset(sub_mtx, eval(as.symbol(fix_pos)) == fix_base), FUN=median)
        df <- merge(df,temp, by.x = 'base', by.y = 'eval(as.symbol(pos))', all=TRUE)
        colnames(df)[ncol(df)] = paste0(pos,"-",fix_pos,fix_base)
      }
    }
    rownames(df) <- df$base
    centered1 <- subset(df, select = -base)
    for (pos in c('n11','n10','n9','n8','n7','n6','n5','n4','n3')){
      for (fix_base in c('A','G','C','T')){
        for (base in c('A','G','C','T')){
          centered1[base, paste0(pos,"-",fix_pos,fix_base)] = df[base, paste0(pos,"-",fix_pos,fix_base)]-
            mean(df[, paste0(pos,"-",fix_pos,fix_base)], na.rm=TRUE)
        }
      }
    }
  }
  # interactions between (-8 to -3) vs (-11 to +1): [NNN +4 TSS]+[NYR +1TSS] datasets are used
  if (fix_pos %in% c('n8','n7','n6','n5','n4','n3')){
    df <- data.frame(base=c('A','G','C','T'))
    sub_mtx <- subset(master_mtx, PolII == pol & lib %in% c('AYR','BYR','ARY') & TSS == '4')
    for (pos in c('n11','n10','n9')){
      for (fix_base in c('A','G','C','T')){
        temp = aggregate(eff ~ eval(as.symbol(pos)), data=subset(sub_mtx, eval(as.symbol(fix_pos)) == fix_base), FUN=median)
        df <- merge(df,temp, by.x = 'base', by.y = 'eval(as.symbol(pos))', all=TRUE)
        colnames(df)[ncol(df)] = paste0(pos,"-",fix_pos,fix_base)
      }
    }
    sub_mtx <- subset(master_mtx, PolII == pol & lib %in% c('AYR','BYR') & TSS == '1')
    for (pos in c('n8','n7','n6','n5','n4','n3','n2','n1','p1')){
      for (fix_base in c('A','G','C','T')){
        temp = aggregate(eff ~ eval(as.symbol(pos)), data=subset(sub_mtx, eval(as.symbol(fix_pos)) == fix_base), FUN=median)
        df <- merge(df,temp, by.x = 'base', by.y = 'eval(as.symbol(pos))', all=TRUE)
        colnames(df)[ncol(df)] = paste0(pos,"-",fix_pos,fix_base)
      }
    }
    rownames(df) <- df$base
    centered1 <- subset(df, select = -base)
    for (pos in c('n11','n10','n9','n8','n7','n6','n5','n4','n3','n2','n1','p1')){
      for (fix_base in c('A','G','C','T')){
        for (base in c('A','G','C','T')){
          centered1[base, paste0(pos,"-",fix_pos,fix_base)] = df[base, paste0(pos,"-",fix_pos,fix_base)]-
            mean(df[, paste0(pos,"-",fix_pos,fix_base)], na.rm=TRUE)
        }
      }
    }
  }
  # interactions between (-2 to +1) vs (-8 to +1): [NYR +1TSS] dataset is used
  if (fix_pos %in% c('n2','n1','p1')){
    df <- data.frame(base=c('A','G','C','T'))
    sub_mtx <- subset(master_mtx, PolII == pol & lib %in% c('AYR','BYR') & TSS == '1')
    n1p1_miss <- data.frame(row.names = c('n1', 'p1'), miss = I(list(c('A','G'),c('C','T'))))
    for (pos in c('n8','n7','n6','n5','n4','n3','n2','n1','p1')){
      for (fix_base in c('A','G','C','T')){
        if ((fix_pos %in% c('n1','p1')) & (fix_base %in% unlist(n1p1_miss[fix_pos,'miss']))){
          temp <- data.frame(mock_bases = c('A','G','C','T'), eff = c(NA,NA,NA,NA))
          df <- merge(df,temp, by.x = 'base', by.y = 'mock_bases', all=TRUE)
        } else {
          temp = aggregate(eff ~ eval(as.symbol(pos)), data=subset(sub_mtx, eval(as.symbol(fix_pos)) == fix_base), FUN=median)
          df <- merge(df,temp, by.x = 'base', by.y = 'eval(as.symbol(pos))', all=TRUE)
        }
        colnames(df)[ncol(df)] = paste0(pos,"-",fix_pos,fix_base)
      }
    }
    rownames(df) <- df$base
    centered1 <- subset(df, select = -base)
    for (pos in c('n8','n7','n6','n5','n4','n3','n2','n1','p1')){
      for (fix_base in c('A','G','C','T')){
        for (base in c('A','G','C','T')){
          centered1[base, paste0(pos,"-",fix_pos,fix_base)] = df[base, paste0(pos,"-",fix_pos,fix_base)]-
            mean(df[, paste0(pos,"-",fix_pos,fix_base)], na.rm=TRUE)
        }
      }
    }
  }
  
  centered1 <- centered1[c('A','G','C','T'),]
  write.csv(t(centered1), paste0(out_folder,pol,'-',fix_pos,"itr-median-centered_pos.csv"), row.names = TRUE)
  
  centered2 <- data.frame(fixbase=paste0(fix_pos,c('A','G','C','T')))
  rownames(centered2) <- centered2$fixbase
  centered2 <- subset(centered2, select = -fixbase)
  for (c in seq(1,ncol(centered1),4)){
    temp = t(centered1[,c:(c+3)])
    pos = strsplit(rownames(temp)[1], split='-')[[1]][1]
    for (base in c('A','G','C','T')){
      for (fix_base in c('A','G','C','T')){
        centered2[paste0(fix_pos,fix_base), paste0(pos,"-",base)] <- 
          temp[paste0(pos,"-",fix_pos,fix_base), base] - mean(temp[, base], na.rm=TRUE)
      }
    }
  }
  centered2 <- centered2[paste0(fix_pos,c('A','G','C','T')),]
  write.csv(centered2, paste0(out_folder,pol,'-',fix_pos,"itr-median-centered_pos_base.csv"), row.names = TRUE)
  
  all_centered <- bind_rows(all_centered,centered2)
}
write.csv(all_centered, paste0(out_folder,pol,"-All_itr-median-centered_pos_base.csv"), row.names = TRUE)

rm(df,centered1,centered2,sub_mtx,temp,n1p1_miss, base,c,fix_base,fix_pos,pos)
rm(all_centered)

## 2.3 median of mut-WT: -8 to +1 based on +1TSS of NYR; -11 to -9 based on +4TSS of NNN ----
NNN4_eff_pol_mtx <- subset(master_mtx, lib %in% c('AYR','BYR','ARY') & TSS == '4')[,c("eff","PolII","TSSvar")] %>%
  spread(key=PolII, value = eff) %>%
  separate(col = TSSvar, into=c('n11','n10','n9','n8_n3'), sep=c(1,2,3), remove=FALSE)
NYR1_eff_pol_mtx <- subset(master_mtx, lib %in% c('AYR','BYR') & TSS == '1')[,c("eff","PolII","TSSvar")] %>%
  spread(key=PolII, value = eff) %>%
  separate(col = TSSvar, into=c('n8','n7','n6','n5','n4','n3','n2','n1','p1'), sep=c(1,2,3,4,5,6,7,8), remove=FALSE)

out_folder = "/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/6-ct4-base_diff_med-mut_wt/"
all_mut <- data.frame()
for (pol in c('G1097D','E1103G','F1086S','H1085Q')){
  mut_wt <- data.frame(base = c('A','G','C','T'))
  for (pos in c('n11','n10','n9')){
    temp = aggregate(eval(as.symbol(pol))-WT ~ eval(as.symbol(pos)), data=NNN4_eff_pol_mtx, FUN=median)
    mut_wt <- merge(mut_wt,temp,by.x = 'base', by.y = 'eval(as.symbol(pos))', all=TRUE)
    colnames(mut_wt)[ncol(mut_wt)] = pos
  }
  for (pos in c('n8','n7','n6','n5','n4','n3','n2','n1','p1')){
    temp = aggregate(eval(as.symbol(pol))-WT ~ eval(as.symbol(pos)), data=NYR1_eff_pol_mtx, FUN=median)
    mut_wt <- merge(mut_wt,temp,by.x = 'base', by.y = 'eval(as.symbol(pos))', all=TRUE)
    colnames(mut_wt)[ncol(mut_wt)] = pos
  }
  rownames(mut_wt) <- mut_wt$base
  mut_wt <- mut_wt[c('A','G','C','T'),c('n11','n10','n9','n8','n7','n6','n5','n4','n3','n2','n1','p1')]
  
  write.csv(t(mut_wt), paste0(out_folder,"n11p1_base_diff_med-",pol,"-wt.csv"), row.names = TRUE)
  
  rownames(mut_wt) <- paste0(pol,'-WT ',rownames(mut_wt))
  all_mut <- bind_rows(all_mut, mut_wt)
}
write.csv(all_mut, paste0(out_folder,"n11p1_base_diff_med-AllMut-wt.csv"), row.names = TRUE)
rm(mut_wt,temp,pos,pol, all_mut, NNN4_eff_pol_mtx,NYR1_eff_pol_mtx)

##### 3. output TSSvar for weblogo for +1 to +9 ####
out_folder = "/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/6-ct4-p1p9pref/"

## percentile
pol = 'WT' # c('G1097D','E1103G','WT','F1086S','H1085Q')
tss = '-8'
d <- 1 # decile
sub_mtx <- subset(master_mtx, PolII == pol & TSS %in% tss)
table(sub_mtx$lib,sub_mtx$TSS)

write.table(sub_mtx[(sub_mtx$eff < quantile(sub_mtx$eff, prob=1-(d-1)*10/100)) & (sub_mtx$eff > quantile(sub_mtx$eff, prob=1-d*10/100)),"TSSvar"],
          paste0(out_folder,pol,"-NNN",tss,"top",(d-1)*10,"_",d*10,".csv"), row.names = FALSE, col.names = FALSE)
summary(sub_mtx[(sub_mtx$eff < quantile(sub_mtx$eff, prob=1-(d-1)*10/100)) & (sub_mtx$eff > quantile(sub_mtx$eff, prob=1-d*10/100)),"eff"])

##### 4. eff- mut vs wt, x-y plot & density histogram #####
# Create a blank placeholder plot:
blankPlot <- ggplot()+geom_blank(aes(1,1)) +
  theme(plot.background = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
  )

# using +1 TSS of NYR
eff_pol_mtx <- subset(master_mtx, lib %in% c('AYR','BYR') & TSS == '1')[,c("eff","PolII","TSSvar")] %>%
  spread(key=PolII, value = eff) %>%
  separate(col = TSSvar, into=c('n8','n7','n6','n5','n4','n3','n2','n1','p1'), sep=c(1,2,3,4,5,6,7,8), remove=FALSE)

eff_pol_mtx$n1p1 <- paste(eff_pol_mtx$n1,eff_pol_mtx$p1,sep = "")
eff_pol_mtx$n8n1p1 <- paste(eff_pol_mtx$n8, eff_pol_mtx$n1,eff_pol_mtx$p1,sep = "")
eff_pol_mtx$n8ABn1p1 <- paste(ifelse(eff_pol_mtx$n8 %in% c('C','G','T'), 'B', 'A'), eff_pol_mtx$n1,eff_pol_mtx$p1,sep = "")

pos_info <- data.frame(pos_col = c('n8', 'n1', 'p1','n1p1','n8n1p1','n8ABn1p1', 'n8ABn1p1', 'n8ABn1p1'), 
                       #  1,2,3,4,5,6,7,8
                       pos_nm = c('-8 base', '-1 base','+1 base', '-1/+1 bases', '-8/-1/+1', '-8/-1/+1', '-8/-1/+1', '-8/-1/+1'),
                       den_max = c(0.06, 0.04, 0.035, 0.04, 0.04, 0.125, 0.125, 0.14),
                       color = I(list(c("#F8766D","#7CAE00","#00BFC4","#C77CFF"),
                                      c('#F8766D','#00BFC4'), c('#999999','#E69F00'),
                                      c("#F8766D","#7CAE00","#00BFC4","#C77CFF"),
                                      #c("ACA","ACG","ATA","ATG","CCA","CCG","CTA","CTG","GCA","GCG","GTA","GTG","TCA","TCG","TTA","TTG"))))
                                      c("#660000","#999999","#FF3300","#999999","#006600","#999999","#00FF33","#999999","#0000FF","#999999","#00CCFF","#999999","#6600CC","#999999","#FF00FF","#999999"),
                                      #c("ACA","ACG","ATA","ATG","BCA","BCG","BTA","BTG")
                                      c("#660000","#FF3300","#006600","#00FF33","#0000FF","#00CCFF","#6600CC","#FF00FF"),
                                      #c("ACA","ACG","ATA","ATG","BCA","BCG","BTA","BTG")
                                      c("#d6604d","#053061","#d6604d","#053061","#67001f","#4393c3","#67001f","#4393c3"),
                                      #c("ACA","ACG","ATA","ATG","BCA","BCG","BTA","BTG")
                                      c("#67001f","#053061","#67001f","#053061","#d6604d","#4393c3","#d6604d","#4393c3"))))
pos_i=8 # which color code?
pos = as.character(pos_info[pos_i,"pos_col"])

pol = "H1085Q" # c('G1097D','E1103G','F1086S','H1085Q')

# x-mut, y-WT
scatterPlot <- 
  ggplot(eff_pol_mtx, aes(x=WT, y=eval(as.symbol(pol)), color=eval(as.symbol(pos)))) + 
  geom_point(size=0.1,alpha=0.02) +
  ylab(pol)+
  xlim(0,100)+ ylim(0,100)+
  scale_color_manual(values = unlist(pos_info[pos_i,"color"])) + 
  labs(colour = as.character(pos_info[pos_i,"pos_nm"])) +
  theme(legend.title = element_text(face="bold"),
        legend.text = element_text(face="bold"),
        legend.background = element_rect(fill = "transparent",colour = NA),
        legend.key = element_rect(fill = "transparent",colour = NA),
        legend.position = c(1.6, 1),
        legend.justification=c("right","bottom"),
        axis.text = element_text(size=10, face="bold", color = "black"),
        axis.title.y = element_text(size=12, face="bold"),
        axis.title.x = element_text(size=12, face="bold",vjust=-1),
        panel.background = element_rect(fill = "white", color = "black", size=2),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.1,0.2,0.6,0.4), "cm"),
        axis.ticks = element_line(color = "black", size=1)
  ) +
  geom_smooth(se = FALSE, size=1, linetype="dashed") +
  geom_abline(intercept = 0, slope = 1, color = "black", lty="dashed")+
  coord_flip()
# Marginal density plot of x (top panel)
xdensity <- 
  ggplot(eff_pol_mtx, aes(x=eval(as.symbol(pol)), fill=eval(as.symbol(pos)))) + 
  geom_density(alpha=.5) + 
  ylim(0,pos_info[pos_i,"den_max"])+
  ylab("Density")+
  xlab(pol)+
  scale_fill_manual(values = unlist(pos_info[pos_i,"color"])) + 
  scale_x_continuous(position = "top", sec.axis = dup_axis(), limits = c(0,100))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", color = "black", size=2),
        panel.grid = element_blank(),
        axis.text = element_text(size=10, face="bold", color = "black"),
        axis.title = element_text(size=12, face="bold"),
        axis.text.x.top = element_blank(),
        axis.ticks.x.top = element_blank(),
        axis.title.x.bottom = element_blank(),
        axis.ticks = element_line(color = "black", size=1),
        plot.margin = unit(c(0.25,0.2,0.2,0.35), "cm")
  )
# Marginal density plot of y (right panel)
ydensity <- 
  ggplot(eff_pol_mtx, aes(y=WT, fill=eval(as.symbol(pos)))) + 
  geom_density(alpha=.5) +
  xlim(0,pos_info[pos_i,"den_max"])+
  xlab("Density")+
  ylab('WT')+
  scale_fill_manual(values = unlist(pos_info[pos_i,"color"])) + 
  scale_y_continuous(position = "right", sec.axis = dup_axis(), limits = c(0,100))+
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white", color = "black", size=2),
        panel.grid = element_blank(),
        axis.text = element_text(size=10, face="bold", color = "black"),
        axis.title = element_text(size=12, face="bold"),
        axis.text.x = element_text(angle=45, vjust=0.8, face="bold"),
        axis.text.y = element_text(hjust=0.5, face="bold"),
        axis.title.x = element_text(vjust=3, face="bold"),
        axis.text.y.right = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.title.y.left = element_blank(),
        axis.ticks = element_line(color = "black", size=1),
        plot.margin = unit(c(0.1,0.1,0.25,0.1), "cm"),
        plot.background = element_rect(fill = "transparent",colour = NA)
  )
# Put the plots together:
grid.arrange(xdensity, blankPlot, scatterPlot, ydensity, 
             ncol=2, nrow=2, widths=c(4, 2), heights=c(2, 4))

# Output as file:
g<- arrangeGrob(xdensity, blankPlot, scatterPlot, ydensity, 
                ncol=2, nrow=2, widths=c(4, 2), heights=c(2, 4))
output_folder = '/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/6-ct4-mut_wt-sca_hist/'
ggsave(file=paste0(output_folder,pol,"_WT-sca_hist.pdf"),g, width=3.88889, height=3.59722, units = "in")

rm(eff_pol_mtx, pos_info,pos_i,pos,pol, blankPlot,scatterPlot,xdensity,ydensity, g,output_folder)

##### 5. check correlation of AYR/BYR +1/+2 and ARY +2/+3 #####
pol_color_info <- data.frame(pol = c('G1097D','E1103G','WT','F1086S','H1085Q'),
                             color = c('#009051','#5B9610','black','#2C96FB','#0433FF'))
lib_tss_info <- data.frame(lib = c('AYR','BYR','ARY'),
                           tsss = I(list(c('1','2'),c('1','2'),c('2','3'))))

pol_i = 3 # which mutant?
lib_i = 3 # which library?
pol = as.character(pol_color_info[pol_i,"pol"])
Lib = as.character(lib_tss_info[lib_i,"lib"])

sub_mtx <- subset(master_mtx, PolII == pol & lib == Lib & TSS %in% unlist(lib_tss_info[lib_i,"tsss"]))[,c('eff','TSSvar','TSS')]
temp_mtx <- spread(sub_mtx, key=TSS, value=eff)
temp_mtx <- subset(temp_mtx, !(is.na(temp_mtx[,2])) & !(is.na(temp_mtx[,3])))
cor(x=temp_mtx[,2],y=temp_mtx[,3])
cor.test(x=temp_mtx[,2],y=temp_mtx[,3], method = "pearson")#$p.value
dim(temp_mtx)

output_folder = '/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/6-ct4-123cor/'
## 5.1 heatscatter for WT- AYR, BYR (or ARY) ----
pdf(file=paste0(output_folder,pol,"-",Lib,".pdf")) # vector image
par(mar = c(3,3,2,1), mgp=c(2,1,0), pty="s")
heatscatter(x=temp_mtx[,2],y=temp_mtx[,3],xlim=c(0,100),ylim=c(0,100), colpal="bl2gr2rd",
            main=NULL,
            xlab = paste0("+", unlist(lib_tss_info[lib_i,"tsss"])[1], " TSS eff"),
            ylab = paste0("+", unlist(lib_tss_info[lib_i,"tsss"])[2], " TSS eff")
)
title(paste0(pol,'-',Lib," +",paste(unlist(lib_tss_info[lib_i,"tsss"]),collapse = "+")), line=0.5)
dev.off()

## 5.2 heatscatter for WT- ARY subgroups ----
temp_mtx <- separate(temp_mtx, col=TSSvar, into=c('n9','n8','n7','n6','n5','n4','n3','n2','n1'), sep=c(1,2,3,4,5,6,7,8), remove=FALSE)
temp_mtx_sub <- subset(temp_mtx, n8 == 'A')
#temp_mtx_sub <- subset(temp_mtx, n8 != 'A')
cor(x=temp_mtx_sub$`2`,y=temp_mtx_sub$`3`)
dim(temp_mtx_sub)

pdf(file=paste0(output_folder,pol,"-",Lib,"-n8A.pdf")) # vector image
#pdf(file=paste0(output_folder,pol,"-",Lib,"-n8B.pdf")) # vector image
par(mar = c(3,3,2,1), mgp=c(2,1,0), pty="s")
heatscatter(x=temp_mtx_sub$`2`,y=temp_mtx_sub$`3`,xlim=c(0,100),ylim=c(0,100), colpal="bl2gr2rd",
            main=NULL,
            xlab = paste0("+", unlist(lib_tss_info[lib_i,"tsss"])[1], " TSS eff"),
            ylab = paste0("+", unlist(lib_tss_info[lib_i,"tsss"])[2], " TSS eff")
)
title(paste0(pol,'-',Lib,"_n8A +",paste(unlist(lib_tss_info[lib_i,"tsss"]),collapse = "+")), line=0.5)
#title(paste0(pol,'-',Lib,"_n8B +",paste(unlist(lib_tss_info[lib_i,"tsss"]),collapse = "+")), line=0.5)
dev.off()

## 5.3 fitting curves for WT vs mut ----
lib_i = 2
Lib = as.character(lib_tss_info[lib_i,"lib"])
all_temp_mtx <- data.frame()
for (pol_i in c(1,2,3,4,5)){
  pol = as.character(pol_color_info[pol_i,"pol"])
  temp <- master_mtx %>%
    subset(PolII == pol & lib == Lib & TSS %in% unlist(lib_tss_info[lib_i,"tsss"]),
           select=c('eff','TSSvar','TSS')) %>%
    spread(key=TSS, value=eff) %>%
    drop_na()
  rownames(temp) <- temp$TSSvar
  colnames(temp) <- c("TSSvar", paste0(pol,"_",colnames(temp)[2:3]))
  
  all_temp_mtx <- merge(all_temp_mtx, temp[,2:3], by=0, all=TRUE)
  rownames(all_temp_mtx) <- all_temp_mtx$Row.names
  all_temp_mtx <- subset(all_temp_mtx, select = -Row.names)
}

pdf(file=paste0(output_folder,"All-",Lib,".pdf")) # vector image
ggplot(all_temp_mtx)+
  scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 20)) +
  scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 20)) +
  xlab(paste0("+", unlist(lib_tss_info[lib_i,"tsss"])[1], " TSS eff")) + 
  ylab(paste0("+", unlist(lib_tss_info[lib_i,"tsss"])[2], " TSS eff")) +
  ggtitle(paste0(Lib," +",paste(unlist(lib_tss_info[lib_i,"tsss"]),collapse = "+"))) +
  theme(
        panel.background = element_rect(fill = "white", color = "black", size=2),
        panel.grid = element_blank(),
        axis.ticks = element_line(color = "black", size=1)
  ) +
  geom_smooth(aes_string(x=paste0("G1097D_",unlist(lib_tss_info[lib_i,"tsss"])[1]),
                         y=paste0("G1097D_",unlist(lib_tss_info[lib_i,"tsss"])[2])),
              se = FALSE, colour=as.character(subset(pol_color_info, pol=='G1097D',select='color')[[1]])) +
  geom_smooth(aes_string(x=paste0("E1103G_",unlist(lib_tss_info[lib_i,"tsss"])[1]),
                         y=paste0("E1103G_",unlist(lib_tss_info[lib_i,"tsss"])[2])),
              se = FALSE, colour=as.character(subset(pol_color_info, pol=='E1103G',select='color')[[1]])) +
  geom_smooth(aes_string(x=paste0("WT_",unlist(lib_tss_info[lib_i,"tsss"])[1]),
                         y=paste0("WT_",unlist(lib_tss_info[lib_i,"tsss"])[2])),
              se = FALSE, colour=as.character(subset(pol_color_info, pol=='WT',select='color')[[1]])) +
  geom_smooth(aes_string(x=paste0("F1086S_",unlist(lib_tss_info[lib_i,"tsss"])[1]),
                         y=paste0("F1086S_",unlist(lib_tss_info[lib_i,"tsss"])[2])),
              se = FALSE, colour=as.character(subset(pol_color_info, pol=='F1086S',select='color')[[1]])) +
  geom_smooth(aes_string(x=paste0("H1085Q_",unlist(lib_tss_info[lib_i,"tsss"])[1]),
                         y=paste0("H1085Q_",unlist(lib_tss_info[lib_i,"tsss"])[2])),
              se = FALSE, colour=as.character(subset(pol_color_info, pol=='H1085Q',select='color')[[1]]))
dev.off()

# check individual with geom_points
pol_i = 1
pol = as.character(pol_color_info[pol_i,"pol"])
ggplot(all_temp_mtx, aes_string(x=paste0(pol,"_",unlist(lib_tss_info[lib_i,"tsss"])[1]),
                                y=paste0(pol,"_",unlist(lib_tss_info[lib_i,"tsss"])[2]))) + 
  geom_point(size=0.1,alpha=0.02, colour=as.character(pol_color_info[pol_i,"color"])) +
  xlim(0,100) + ylim(0,100) +
  xlab(paste0("+", unlist(lib_tss_info[lib_i,"tsss"])[1], " TSS eff")) + 
  ylab(paste0("+", unlist(lib_tss_info[lib_i,"tsss"])[2], " TSS eff")) +
  ggtitle(paste0(pol, " ", Lib," +",paste(unlist(lib_tss_info[lib_i,"tsss"]),collapse = "+"))) +
  theme_bw() +
  geom_smooth(se = FALSE, colour=as.character(pol_color_info[pol_i,"color"]))

rm(lib_i,Lib,lib_tss_info, pol_i,pol,pol_color_info, sub_mtx,temp_mtx,temp_mtx_sub, all_temp_mtx,temp)

##### 6. stat figures: CV vs reads #####
inp_folder = '/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/2p-reps_RNAstat/'

for (lib in c('AYR','BYR','ARY')){
  for (pol in c('G1097D','E1103G','WT','F1086S','H1085Q')){
    stat <- read.csv(paste0(inp_folder,lib,"_",pol,"-pDs_B12Cmb-reps_RNAstat.csv")) # generated by <2p-reps_RNAstat.py>

    pdf(file=paste0(inp_folder,lib,"_",pol,"-pDs_B12Cmb-reps_RNAstat-CV_reads.pdf")) # vector image
    heatscatter_vis(x=stat[, "Sum"], y=stat[, "CV"],
                    main=paste0(lib,"_",pol),
                    xlab="Total matched RNA reads", ylab="Coefficient of variation",
                    ylim=c(0, 1.7),
                    tick=TRUE,
                    diagonal=FALSE,
                    hline=0.5)
    dev.off()
  }
}

##### 7. reproducibility figures #####
inp_folder = '/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/2p-check/'
for (lib in c('AYR','BYR','ARY')){
  if (lib=='ARY'){tss='2'} else {tss='1'}
  eff_mtx <- read.csv(paste0(inp_folder,lib,'_final-reps_pDs_B12Cmb-TSS_',tss,'eff.csv'), row.names=1) # generated by <2p-check.py>
  
  cp_info <- data.frame(x = colnames(eff_mtx)) # to record comparison results
  for (s in seq(1,15,3)){
    cp_info[s,"y"] <- colnames(eff_mtx)[s+1]
    cp_info[s,"cor"] <- cor(x=eff_mtx[, s], y=eff_mtx[, s+1], use="complete.obs")
    
    pdf(file=paste0(inp_folder,lib,"_final-pDs_B12Cmb-TSS_",tss,"eff-",strsplit(colnames(eff_mtx)[s], split='_')[[1]][2],"-",
                    strsplit(colnames(eff_mtx)[s], split='_')[[1]][3],"_",
                    strsplit(colnames(eff_mtx)[s+1], split='_')[[1]][3],".pdf")) # vector image
    heatscatter_vis(x=eff_mtx[, s], y=eff_mtx[, s+1],
                    main=paste0(colnames(eff_mtx)[s],' vs ',strsplit(colnames(eff_mtx)[s+1], split='_')[[1]][3]),
                    xlab=colnames(eff_mtx)[s], ylab=colnames(eff_mtx)[s+1],
                    xlim=c(0, 100),
                    ylim=c(0, 100),
                    tick=TRUE,
                    diagonal=TRUE
                    )
    dev.off()
  }
  write.table(cp_info, paste0(inp_folder,lib,'_final-reps_pDs_B12Cmb-cp_cor.csv'), sep=',', row.names = FALSE, col.names = TRUE)
}

##### 8. efficiency histograms #####
# to export frequency data of efficiency distribution of all sequence variants for visualization
out_folder = '/bgfs/ckaplan/Yunye/3-TSS_sequence_library/7-poolDs_cmbTs/6-ct4-TSSvar-cnt_dist/'
for (pol in c('G1097D','E1103G','WT','F1086S','H1085Q')){
  sub_mtx <- subset(master_mtx, PolII == pol)
  
  his <- data.frame(matrix(ncol = 0, nrow = length(seq(0,100,2.5))-1))
  his$mids <- hist(sub_mtx$eff, breaks=seq(0,100,2.5))$mids
  his$counts <- hist(sub_mtx$eff, breaks=seq(0,100,2.5))$counts
  write.csv(his, paste0(out_folder, "TSSvar-cnt_dist-",pol,".csv"), row.names = TRUE)
}
rm(pol,sub_mtx,his)
